export enum ModalEnum {
  KID_CREATE = "kid-create",
  KID_EDIT = "kid-edit",
  VACCINATION_TAG_CREATE = "vaccination-tag-create",
  VACCINATION_TAG_EDIT = "vaccination-tag-edit",
  VACCINATION_CREATE = "vaccination-create",
  VACCINATION_EDIT = "vaccination-edit",
  PARENT_CREATE = "parent-create",
  PARENT_EDIT = "parent-edit",
  ABSENCE_CREATE = "absence-create",
  ABSENCE_EDIT = "absence-edit",
  ABSENCE_TAG_CREATE = "absence-tag-create",
  ABSENCE_TAG_EDIT = "absence-tag-edit",
  NOTE_CREATE = "note-create",
  NOTE_EDIT = "note-edit",
  NOTE_TAG_CREATE = "note-tag-create",
  NOTE_TAG_EDIT = "note-tag-edit",
}
